### ISSUE TITLE
Обмежити право на зміни в мастер папці без пул реквеста

### ISSUE THREAD

**Issue by pupenasan** [romamirkevich/PLCBeginner#1]
Деталі на https://github.com/pupenasan/ProgIngContrSystems/blob/master/%D0%9B%D0%B5%D0%BA%D1%86/GitHub.md

**Comment by pupenasan** [comment]
@romamirkevich  ти як 'Адмін' маєш це зробити, бо поламаємо все )

**Comment by romamirkevich** [comment]
виконано

**Comment by pupenasan** [comment]
у мене є можливість зробити мердж навіть без апрува, @romamirkevich треба поправити

**Comment by romamirkevich** [comment]
готово
