### ISSUE TITLE
Перенести та класифікувати існуючі лекції в MarkDown

### ISSUE THREAD

**Issue by pupenasan** [romamirkevich/PLCBeginner#3]
Існуючі презентації перевести (механічно) в формат Markdown:
- [x] у корені робочої папки створити папку `лекції`
- [x] у папці `лекції` створити папку [media]
- [x] у папку [media] закинути усі існуючі презентації PPTX (вони будуть системою прийматися як бінарники, ну і нічого страшного)  
- [x] зберегти рисунки з презентацій як *.PNG у папку `media` 
- [x] зробити MarkDown версії, тобто посилання на рисунки повставляти в файли MD, однойменні до PPTX
[Приклад архітектури дисципліни](https://github.com/pupenasan/ProgIngContrSystems)

**Comment by pupenasan** [comment]
@romamirkevich поки прийдеться тобі, але якщо когось підключиш, то делегуємо іншим

**Comment by romamirkevich** [comment]
готово

**Comment by pupenasan** [comment]
PPTX треба перенести в папку Media

**Comment by romamirkevich** [comment]
готово
