### ISSUE TITLE
Лекція "Змінні в М221/222" 

### ISSUE THREAD

**Issue by pupenasan** [romamirkevich/PLCBeginner#5]
Не знайшов лекції по правилам адерсації, якщо її по факту немає, треба зробити

**Comment by pupenasan** [comment]
@romamirkevich знайшов ці лекції в "програмній структурі ПЛК", але вона якось пересікається з "1 режими роботи", може варто її переробити в адресація змінних?

**Comment by romamirkevich** [comment]
думаю так

**Comment by pupenasan** [comment]
@romamirkevich ти вже приступав?

**Comment by pupenasan** [comment]
@OlehKlym89  підключайся
