### ISSUE TITLE
Лабораторна робота 3 (Функціональні блоки)

### ISSUE THREAD

**Issue by pupenasan** [romamirkevich/PLCBeginner#7]
Використання основних функціональних блоків
- [x] (Частина 1) перевірка таймерів, лічильників ...
- [x] (Частина 2) вирішення задачки: опис алгоритму, програма для рішення, опис кроково-орієнтованого підходу, написання програми, методика перевірки
- [x] (Частина 3) написання власної програми користувача

**Comment by pupenasan** [comment]
@matsebuladv треба зробити

**Comment by matsebuladv** [comment]
зробив ч.1

**Comment by matsebuladv** [comment]
Перший варіант зроблений
